# Catppuccin Macchiato theme for fast-syntax-highlighting

[base]
default                                 = none
unknown-token                           = 203,bold
commandseparator                        = 183
subtle-separator                        = 242

[command-point-of-interest]
reserved-word                           = 183,bold
alias                                   = 150
suffix-alias                            = 150
global-alias                            = 150
builtin                                 = 150
function                                = 150
command                                 = 150
precommand                              = 150,underline
hashed-command                          = 150
subcommand                              = 183

[paths]
path                                    = 216,underline
path-to-dir                             = 216,underline
path_pathseparator                      = 242
pathseparator                           = 242
globbing                                = 218
globbing-ext                            = 218,bold

[brackets]
single-sq-bracket                       = 152,bold
double-sq-bracket                       = 152,bold
double-paren                            = 152,bold
paired-bracket                          = 152,bold
bracket-error                           = 203,bold
bracket-level-1                         = 117,bold
bracket-level-2                         = 150,bold
bracket-level-3                         = 223,bold

[arguments]
single-hyphen-option                    = 223
double-hyphen-option                    = 223
double-hyphen-option-argument           = 216
optarg-string                           = 150
optarg-number                           = 216

[quoting]
back-quoted-argument                    = 218
back-quoted-argument-unclosed           = 203
back-quoted-argument-delimiter          = 218,bold
single-quoted-argument                  = 150
double-quoted-argument                  = 150
dollar-quoted-argument                  = 152
dollar-quoted-argument-unclosed         = 203
back-or-dollar-double-quoted-argument   = 152
back-dollar-quoted-argument             = 152

[assignment]
assign                                  = 189
assign-array-bracket                    = 152
variable                                = 189

[redirection]
redirection                             = 152,bold
here-string-tri                         = 150
here-string-text                        = 150
here-string-var                         = 152

[history]
history-expansion                       = 218,bold

[math]
matherr                                 = 203,bold
mathnum                                 = 216
mathvar                                 = 189

[comments]
comment                                 = 242

[case]
case-input                              = 150
case-parentheses                        = 183
case-condition                          = 183

[loops]
forvar                                  = 189
fornum                                  = 216
foroper                                 = 183
forsep                                  = 242

[descriptors]
exec-descriptor                         = 183

[corrections]
correct-subtle                          = 242
incorrect-subtle                        = 203
subtle-bg                               = 236
recursive-base                          = 249
secondary                               = 249
